sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gdb libboost-dev

script:
  - echo ${COMPILER}
  - echo ${CXX}
  - $CXX --version
  - if [[ "$COMPILER}" == "g++" ]]; then export NO_CXX14=true; fi
  - ./run_test.sh
